apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-loki.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               example-app.*
        Path              /var/log/containers/example-app-*.log
        Parser            docker
        DB                /var/log/flb-example-app.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [INPUT]
        Name tail
        Tag sysapp.gen.log.mail
        Parser sys_log_file
        Path /var/log/mail
        db /var/log/mail.db
    [INPUT]
        Name tail
        Tag sysapp.gen.log.secure
        Parser sys_log_file
        Path /var/log/secure
        db /var/log/secure.db
    [INPUT]
        Name tail
        Tag sysapp.gen.log.messages
        Parser sys_log_file
        Path /var/log/messages
        db /var/log/messages.db
    [INPUT]
        Name tail
        Tag sysapp.gen.log.cron
        Parser sys_log_file
        Path /var/log/cron
        db /var/log/cron.db
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               web-api
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     web-api.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  Off
        K8S-Logging.Exclude Off
    [FILTER]
        Name modify
        Match sysapp.gen.log.mail
        Set app syslog
        Set file /var/log/mail
    [FILTER]
        Name modify
        Match sysapp.gen.log.secure
        Set app syslog
        Set file /var/log/secure
    [FILTER]
        Name modify
        Match sysapp.gen.log.messages
        Set app syslog
        Set file /var/log/messages
    [FILTER]
        Name modify
        Match sysapp.gen.log.cron
        Set app syslog
        Set file /var/log/cron
  output-loki.conf: |
    [OUTPUT]
        Name          loki/http
        Match         *
        Url           http://loki.monitoring.svc:3100/loki/api/v1/push
        Http_Method   POST
        Json_Date_Key ts
        Header        X-Scope-OrgID "1"