apiVersion: v1
kind: Service
metadata:
  name: flb-metric
  namespace: monitoring
  labels:
    app: fluent-bit
spec:
  type: ClusterIP
  selector:
    app: fluent-bit
  ports:
  - name: fluentbit
    port: 2020
    targetPort: 2020