apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flb-metric
  namespace: monitoring
  labels:
    app: fluent-bit
spec:
  endpoints:
  - targetPort: 2020
    interval: 30s
    path: /api/v1/metrics/prometheus
  selector:
    matchLabels:
      app: fluent-bit