apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules-conf
  namespace: monitoring
data:
  node_rules.yml: |
    groups:
    - name: container_cpu
      rules:
      - record: container_cpu_usage_percent
        expr: 100 - (avg by (instance, container) (irate(container_cpu_usage_seconds_total{container="web-api"}[5m])) * 100)

    - name: container_memory
      rules:
      - record: container_memory_usage_percent
        expr: (container_memory_usage_bytes{container="web-api"} / container_spec_memory_limit_bytes{container="web-api"}) * 100

    - name: alert_rules
      rules:
        - alert: HighCPULoad
          expr: container_cpu_usage_percent > 70
          labels:
            severity: warning
          annotations:
            description: 'High CPU load detected on {{ $labels.instance }}'
            summary: 'High CPU Load'

        - alert: RAMMemoryFree30Percent
          expr: container_memory_usage_percent > 70
          labels:
            severity: warning
