apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules-conf
  namespace: monitoring
data:
  node_rules.yml: |
    groups:
    - name: node_cpu
      rules:
      - record: node_cpu_usage_percent
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
    
    - name: node_memory
      rules:
      - record: node_memory_MemFree_percent
        expr: container_memory_usage_bytes{container="web-api"} / container_memory_limit_bytes{container="web-api"} * 100
    
    - name: alert_rules
      rules:
        - alert: HighCPULoad
          expr: 100 - (avg by (instance) (irate(container_cpu_usage_seconds_total{container="web-api"}[5m])) * 100) > 70
          labels:
            severity: warning
          annotations:
            description: 'High CPU load detected on {{ $labels.instance }}'
            summary: 'High CPU Load'

        - alert: RAMMemoryFree30Percent
          expr: container_memory_usage_bytes{container="web-api"} / container_memory_limit_bytes{container="web-api"} * 100 > 70
          labels:
            severity: warning